---
- name: copy a file
  hosts: localhost 
  vars_files:
    - /home/vignesh/ansible/iterate_hosts.yml
  tasks:
    - name: testing
      debug:
        msg: "the message was {{ patching_day1 }} {{ patching_group1 }} {{ server1 }} "
...
  
