---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: find out the path
      script: /var/lib/awx/projects/_18__snow_project/Reading_Excel_file.py
