---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: find out the path
      shell:         
        cmd: python /var/lib/awx/projects/_13__new_change_job/Reading_Excel_file.py
