---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: find out the path
      shell: pwd
      register: cwd
    - debug:
      debug: var=cwd.stdout
