---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: find out the path
      command: Reading_Excel_file.py
      args:
        chdir: /var/lib/awx/projects/_8__change_creation/  
      
