---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Run python file
      shell:
        cmd: python https://github.com/sundararajanr/Patch/blob/master/Reading_Excel_file.py
      
